general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/hrittick/Pictures/Wallpapers/b-624.jpg
    blur_passes = 2 # Increased blur for a cleaner look
    contrast = 0.89
    brightness = 0.81
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(205, 214, 244) # Subpixel Green
    inner_color = rgb(30, 30, 46)
    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    placeholder_text = <span foreground="##89dceb">password</span>
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(205, 214, 244) # Subpixel Green
    font_size = 120
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%a, %d %b')"
    color = rgb(205, 214, 244) # Subpixel Green
    font_size = 18
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, -15
    halign = center
    valign = center
}