general {
    lock_cmd = pidof hyprlock || hyprlock       # command run when hypridle requests a lock
    before_sleep_cmd = loginctl lock-session    # command run before system goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # command run after waking up to ensure display is on
}

# Dim screen after 2.5 minutes
listener {
    timeout = 150                                 
    on-timeout = brightnessctl set 10%          # Requires brightnessctl package
    on-resume = brightnessctl set 20%
}

# Lock screen after 5 minutes
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# Turn off display after 5.5 minutes
listener {
    timeout = 330                                 
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on          
}

# Suspend system after 10 minutes
listener {
    timeout = 600                                 
    on-timeout = systemctl suspend                
}
